### ISSUE TITLE
Adding Free Functions to vapi

### ISSUE THREAD

**Issue by Charadon** [lxmcf/raylib-vapi#2]
Out of curiosity have you attempted this? If not, I can see about testing it, and seeing if it works, and if it does, contribute it, of course. The obvious advantage is that you won't have to call the `unload_x` functions manually all the time. =)

**Comment by lxmcf** [comment]
I have considered it for sure, however wanted the main VAPI to be 1 to 1 with raylib.

I have plans to make a more OOP style VAPI and will likely use the free functions for that.

**Comment by Charadon** [comment]
> I have considered it for sure, however wanted the main VAPI to be 1 to 1 with raylib.
> 
> I have plans to make a more OOP style VAPI and will likely use the free functions for that.

Well, lemme know when you start on the OOP style vapi, as i'll help. =) You can find me on the fediverse at `@charadon@mb.iotib.net`
